# Site settings
title: iDigPhylo
email: matt@badmatt.com
description: > # this means to ignore newlines until "baseurl:"
  Copyright 2015 Matthew Collins, CC-BY
baseurl: "/idigphylo/" # the subpath of your site, e.g. /blog/
url: "http://badmatt.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
